# CodeReview Agent Configuration
# ==============================

# LLM Configuration
llm:
  provider: minimax
  apiKey: ${{ secrets.LLM_API_KEY }}
  model: abab6.5s-chat

# Critical paths - high risk areas
criticalPaths:
  - python/src/codereview

# Exclude patterns
excludePatterns:
  - "*.test.py"
  - "**/__pycache__/**"
  - ".venv/**"
  - "node_modules/**"

# Cache configuration
cache:
  ttl: 7
  forceRefresh: false

# Output configuration
output:
  prComment: true
  reportPath: .codereview-agent/output
  reportFormat: markdown
